### ISSUE TITLE
Wrong fee coefficient for Redemption

### ISSUE THREAD

**Issue by KStasi** [mstable/mStable-contracts#99]
Probably, should be set to `redemptionFee`
https://github.com/mstable/mStable-contracts/blob/d4c30010dff98eccabafb3fdf9d79a6da3f32b4e/contracts/masset/Masset.sol#L543

**Comment by alsco77** [comment]
Hey @KStasi , many thanks for pointing this out to us. Actually (counter intuitively) this is correct and intended. The `redemptionFee` is a seperate fee recently implemented specifically for the `redeemMasset` function.

*Note: mStable has an active [bug bounty](https://docs.mstable.org/protocol/security/mstable-bug-bounty). If the bug affects running code then you should follow the responsible disclosure guidelines and submit it directly to the team in order to be eligible for a reward*
